name: console-conf
base: core24
build-base: devel
summary: console-conf Ubuntu Core first boot experience
description: |
  console-conf provide device onboarding experience for
  Ubuntu Core systems. User can configure network and
  assume ownership of the system.

grade: devel
confinement: strict
adopt-info: set-metadata

environment:
  PATH: $SNAP/usr/bin:$SNAP/usr/sbin:$PATH
  PYTHONHOME: $SNAP/usr
  PYTHON: $SNAP/usr/bin/python3
  PYTHONPATH: $SNAP/usr/share/subiquity:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.11
  PYTHONIOENCODING: utf-8
  SUBIQUITY_ROOT: $SNAP
  SNAP_CONFINEMENT: "strict"

apps:
  console-conf:
    command: usr/bin/python3 $SNAP/usr/share/subiquity/console-conf-tui
    plugs:
      # TODO: controversial interfaces disabled to enable store uploads
      - hardware-observe
      - network
      - network-control
      - network-observe
      - network-setup-control
      # - run-console-conf
      # - var-log-console-conf
      # - terminal-control
      # - snapd-control

  wait:
    command: usr/share/subiquity/console-conf-wait

# TODO build probert and console-conf as debs so that dependencies are pulled in
# automatically

parts:
  probert:
    plugin: nil
    source: https://github.com/canonical/probert.git
    source-type: git
    # following branch server/jammy
    source-commit: 253acbe1480fba69d12d6e72f53412da79e27410
    override-build: |
      unset LD_FLAGS
      unset LD_LIBRARY_PATH
      dpkg-buildpackage -b -uc -us -Zgzip -zfast
      mkdir -p "${CRAFT_PART_BUILD}/local-debs"
      source="$(dpkg-parsechangelog -SSource)"
      version="$(dpkg-parsechangelog -SVersion)"
      arch="$(dpkg --print-architecture)"
      dcmd mv "../${source}_${version}_${arch}.changes" "${CRAFT_PART_BUILD}/local-debs"
      cp -r debian/tmp/usr  ${CRAFT_PART_INSTALL}
      dpkg -x ${CRAFT_PART_BUILD}/local-debs/probert_*.deb ${CRAFT_PART_INSTALL}
      dpkg -x ${CRAFT_PART_BUILD}/local-debs/probert-common_*.deb ${CRAFT_PART_INSTALL}
      dpkg -x ${CRAFT_PART_BUILD}/local-debs/probert-network_*.deb ${CRAFT_PART_INSTALL}
      dpkg -x ${CRAFT_PART_BUILD}/local-debs/probert-storage_*.deb ${CRAFT_PART_INSTALL}
    stage:
      - usr

  subiquity:
    plugin: nil
    source: https://github.com/canonical/subiquity.git
    source-type: git
    # https://github.com/canonical/subiquity/commit/0aaade5c53baf53e25dd4dfe8d003dd42cc395e8
    source-commit: 0aaade5c53baf53e25dd4dfe8d003dd42cc395e8
    override-build: |
      version=$(git describe --tags)
      unset LD_FLAGS
      unset LD_LIBRARY_PATH
      dpkg-buildpackage -b -uc -us -Zgzip -zfast
      mkdir -p "${CRAFT_PART_BUILD}/local-debs"
      source="$(dpkg-parsechangelog -SSource)"
      version="$(dpkg-parsechangelog -SVersion)"
      arch="$(dpkg --print-architecture)"
      dcmd mv "../${source}_${version}_${arch}.changes" "${CRAFT_PART_BUILD}/local-debs"
      dpkg -x ${CRAFT_PART_BUILD}/local-debs/console-conf_*.deb ${CRAFT_PART_INSTALL}
      dpkg -x ${CRAFT_PART_BUILD}/local-debs/subiquitycore_*.deb ${CRAFT_PART_INSTALL}
      # record the version
      echo "${version}" > ${CRAFT_PART_INSTALL}/usr/share/subiquity/version-info
    stage:
      - usr/share/subiquity/
      - -usr/share/subiquity/console-conf-wait

  set-metadata:
    plugin: dump
    # too naive to assume that project is always a git clone?
    source: .
    after:
      - subiquity
    override-build: |
      test -f "${CRAFT_STAGE}/usr/share/subiquity/version-info"
      version="$(cat ${CRAFT_STAGE}/usr/share/subiquity/version-info)"
      version="${version}+g$(git describe --always)"
      craftctl set version="${version}"

  python:
    plugin: nil
    stage-packages:
      - python3
      - python3-minimal
      - python3.12-minimal
      - libpython3-stdlib
      - libpython3.12-stdlib
      - libpython3.12-minimal
      - libsystemd0
      - python3-aiohttp
      - python3-apport
      - python3-attr
      - python3-bson
      - python3-certifi
      - python3-chardet
      - python3-debian
      - python3-idna
      - python3-jsonschema
      - python3-minimal
      - python3-multidict
      - python3-oauthlib
      - python3-openssl
      - python3-pkg-resources
      - python3-pyroute2
      - python3-pyrsistent
      - python3-pyudev
      - python3-requests
      - python3-requests-unixsocket
      - python3-six
      - python3-systemd
      - python3-typing-extensions
      - python3-urllib3
      - python3-urwid
      - python3-wcwidth
      - python3-yaml
      - python3-yarl

  static:
    plugin: dump
    source: static

# TODO: controversial interfaces disabled to enable store uploads

# plugs:
#   run-console-conf:
#     interface: system-files
#     write:
#       - /run/console-conf
#   var-log-console-conf:
#     interface: system-files
#     write:
#       - /var/log/console-conf
#   terminal-control:
#     interface: custom-device

# slots:
#   terminal-devices:
#     interface: custom-device
#     custom-device: terminal-control
#     # XXX this could use x11/wayland/mir interface, but we only need a subset of
#     # the permissions provided by each
#     devices:
#       - /dev/tty[0-9]
#       - /dev/ttyS[0-9]
#     udev-tagging:
#       - kernel: tty[0-9]
#         subsystem: tty
#       - kernel: ttyS[0-9]
#         subsystem: tty

build-packages:
  - apt-utils
  - build-essential
  - debhelper-compat
  - devscripts
  - dh-python
  - fakeroot
  - gettext
  - iso-codes
  - libnl-genl-3-dev
  - libnl-route-3-dev
  - lsb-release
  - pkg-config
  - python3
  - python3-all-dev
  - python3-coverage
  - python3-distutils-extra
  - python3-flake8
  - python3-jsonschema
  - python3-mock
  - python3-nose
  - python3-pip
  - python3-pyudev
  - python3-testtools
  - python3-yaml
