name: Build on LP, run spread tests, publish to edge

on:
  push:
    branches:
      - main

concurrency:
  group: lp-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_to_edge:
    # self-hosted runner so we can access launchpad
    runs-on: self-hosted
    steps:
      - name: Publish to edge
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        uses: snapcore/system-snaps-cicd-tools/action-publish-edge@main
        with:
          # TODO enable tests once we have them
          run_tests: false
          track: "latest"
          # add riscv64 once we have a core24 snap for it, see
          # https://launchpad.net/~ubuntu-core-service/+snap/core24
          architectures: arm64,amd64,armhf
