name: Snap test build (snapcore actions)

on:
  pull_request:
    branches:
      - main

concurrency:
  group: snapcore-build-${{ github.head_ref || github.run_id }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
      id: build
      with:
        # edge has a fix for https://bugs.launchpad.net/snapcraft/+bug/2055322
        snapcraft-channel: latest/edge

    - uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ${{ steps.build.outputs.snap }}
        retention-days: 5
