name: Build on LP, run spread tests, publish to edge

on:
  push:
    branches:
      - main

concurrency:
  group: lp-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_to_edge:
    # self-hosted runner so we can access launchpad
    runs-on: self-hosted
    steps:
      - name: Publish to edge
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        uses: snapcore/system-snaps-cicd-tools/action-publish-edge@main
        with:
          run_tests: true
          track: "latest"
          architectures: arm64,amd64,armhf,riscv64
          spread_suites: "google-nested:"
          snapcraft_channel: "latest/edge"
