name: Snap test build (snapcore actions)

on:
  pull_request:
    branches:
      - main

concurrency:
  group: snapcore-build-${{ github.head_ref || github.run_id }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
      id: build
      with:
        # edge has a fix for https://bugs.launchpad.net/snapcraft/+bug/2055322
        snapcraft-channel: latest/edge

    - uses: actions/upload-artifact@v4
      with:
        name: snap
        path: ${{ steps.build.outputs.snap }}
        retention-days: 5

  test:
    needs:
      - build
    runs-on: self-hosted
    steps:
    - name: Workspace cleanup
      run: |
        rm -rf "${{ github.workspace }}"
        mkdir "${{ github.workspace }}"
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: snap
        path: "${{ github.workspace }}/console-conf-artifact"
    - name: Prepare for spread tests
      run: |
        shopt -s nullglob
        mv -v console-conf-artifact/*.snap .

    - name: Run spread tests
      run: |
        rm -rf ./artifacts
        # TODO tests for other archs?
        spread -artifacts ./artifacts google-nested:

    - name: Fixup spread artifacts
      if: always()
      # upload-artifact does not like : in file or directory names
      run: |
        if [ ! -d artifacts ]; then
            echo "nothing to do"
            exit 0
        fi

        shopt -s nullglob
        for f in ./artifacts/*; do
            mv -v "$f" "${f//:/-}"
        done

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-artifacts
        path: artifacts
        retention-days: 5

    - name: Discard spread workers
      if: always()
      run: |
        shopt -s nullglob
        for r in .spread-reuse.*.yaml; do
          spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')"
        done
